export default {
  Category: [
    {
      id: '1',
      category: 'Wingback Chairs',
    },
    {
      id: '2',
      category: 'Club Chair',
    },
    {
      id: '3',
      category: 'Egg Chair',
    },
    {
      id: '4',
      category: 'Tulip Chair',
    },
    {
      id: '5',
      category: 'Desk Chair',
    },
  ],
  Product: [
    {
      id: '1',
      categoryid: '1',
      product: 'Westeros Traditional Wingback Chair',
      image: require('./CsAllAssets/Images/1.png'),
      dis: 'White & Blue Floral, Polyester, Textile',
      price: '278',
    },
    {
      id: '2',
      categoryid: '1',
      product: 'Christopher Knight Home Toddman Wingback Chair',
      image: require('./CsAllAssets/Images/2.png'),
      dis: 'Dark Teal, Textile',
      price: '221',
    },
    {
      id: '3',
      categoryid: '1',
      product: 'GDF Studio Elizabeth Tufted Fabric Wingback Chair',
      image: require('./CsAllAssets/Images/3.png'),
      dis: 'Light Beige, Textile',
      price: '283',
    },
    {
      id: '4',
      categoryid: '1',
      product: 'NIBESSER Wingback Chair',
      image: require('./CsAllAssets/Images/4.png'),
      dis: 'Diamond Grey, Polyester',
      price: '215',
    },
    {
      id: '5',
      categoryid: '1',
      product: 'Westeros Traditional Wingback Chair',
      image: require('./CsAllAssets/Images/5.png'),
      dis: 'Wheat, Polyester, Textile',
      price: '298',
    },
    {
      id: '6',
      categoryid: '2',
      product: 'Didihou Club Chair',
      image: require('./CsAllAssets/Images/6.png'),
      dis: '85% Polyester/15% Spandex',
      price: '143',
    },
    {
      id: '7',
      categoryid: '2',
      product: 'NIBESSER Club Chair',
      image: require('./CsAllAssets/Images/7.png'),
      dis: 'Teal, Polyester',
      price: '175',
    },
    {
      id: '8',
      categoryid: '2',
      product: 'SearchI Club Chair',
      image: require('./CsAllAssets/Images/8.png'),
      dis: 'Floral Pint 4',
      price: '155',
    },
    {
      id: '9',
      categoryid: '2',
      product: 'SearchI Club Chair Slipcover Burgundy',
      image: require('./CsAllAssets/Images/9.png'),
      dis: '80% Polyester and 20%Spandex',
      price: '169',
    },
    {
      id: '10',
      categoryid: '2',
      product: 'NIBESSER Club Chair Balck',
      image: require('./CsAllAssets/Images/10.png'),
      dis: 'Black, Polyester',
      price: '126',
    },
    {
      id: '11',
      categoryid: '3',
      product: 'Island Gale Luxury Egg Chair',
      image: require('./CsAllAssets/Images/11.png'),
      dis: 'Latte Rattan/Charcoal Cushion, Rattan',
      price: '122',
    },
    {
      id: '12',
      categoryid: '3',
      product: 'Christopher Knight Home Egg Chair',
      image: require('./CsAllAssets/Images/12.png'),
      dis: 'Multi-brown and Tan, Water Resistant Fabric',
      price: '132',
    },
    {
      id: '13',
      categoryid: '3',
      product: 'Modway Lounge Egg Chair',
      image: require('./CsAllAssets/Images/13.png'),
      dis: 'Turquoise, Rattan',
      price: '114',
    },
    {
      id: '14',
      categoryid: '3',
      product: 'Best Choice Products Hanging Egg Chair',
      image: require('./CsAllAssets/Images/14.png'),
      dis: 'Black, Steel',
      price: '120',
    },
    {
      id: '15',
      categoryid: '3',
      product: 'SQINAA Hanging Egg Chair',
      image: require('./CsAllAssets/Images/15.png'),
      dis: 'Polyester',
      price: '115',
    },
    {
      id: '16',
      categoryid: '4',
      product: 'HTL Dining Tulip Chair',
      image: require('./CsAllAssets/Images/16.png'),
      dis: 'Solid Back',
      price: '99',
    },
    {
      id: '17',
      categoryid: '4',
      product: 'Modway Lippa Mid-Century Tulip Chair',
      image: require('./CsAllAssets/Images/17.png'),
      dis: 'Tan, Plastic',
      price: '95',
    },
    {
      id: '18',
      categoryid: '4',
      product: 'Eero Saarinen Style Tulip Chair',
      image: require('./CsAllAssets/Images/18.png'),
      dis: 'Grey, Polypropylene',
      price: '80',
    },
    {
      id: '19',
      categoryid: '4',
      product: 'DHP C013701 Mid Century Tulip Chair',
      image: require('./CsAllAssets/Images/19.png'),
      dis: 'Black, Wood',
      price: '85',
    },
    {
      id: '20',
      categoryid: '4',
      product: 'PoliVaz Eero Saarinen Style Tulip Chair',
      image: require('./CsAllAssets/Images/20.png'),
      dis: 'White, Polypropylene',
      price: '79',
    },
    {
      id: '21',
      categoryid: '5',
      product: 'Amazon Basics Office Desk Chair',
      image: require('./CsAllAssets/Images/21.png'),
      dis: 'Brown, Polyurethane bonded leather',
      price: '75',
    },
    {
      id: '22',
      categoryid: '5',
      product: 'Home Office Chair Ergonomic Desk Chair',
      image: require('./CsAllAssets/Images/22.png'),
      dis: 'Black, Mesh',
      price: '67',
    },
    {
      id: '23',
      categoryid: '5',
      product: 'SMUGDESK Ergonomic Desk Chair',
      image: require('./CsAllAssets/Images/23.png'),
      dis: 'Grey, Mesh',
      price: '82',
    },
    {
      id: '24',
      categoryid: '5',
      product: 'BestOffice PC Gaming Chair',
      image: require('./CsAllAssets/Images/24.png'),
      dis: 'Black/White Leather',
      price: '85',
    },
    {
      id: '25',
      categoryid: '5',
      product: 'Amazon Basics Classic Puresoft Desk Chair',
      image: require('./CsAllAssets/Images/25.png'),
      dis: 'Black, Polyurethane bonded leather',
      price: '88',
    },
  ],
};
